name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    permissions: 
      contents: write
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint with auto-fix
        run: npx next lint --fix

      - name: Push the formatted code if needed.
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "fix!: [ci skip] eslint format."

      # - name: Configure Netlify CLI
      #   run: |
      #     npm install netlify-cli
      #     npm install @netlify/plugin-nextjs

      # - name: Deploy to Netlify (production)
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run:
      #     netlify deploy --build --prod
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   timeout-minutes: 10

      # - name: Deploy to Netlify (draft)
      #   if: github.event_name == 'pull_request'
      #   run:
      #     netlify deploy --build
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #   timeout-minutes: 10
