name: Deploy on VNS Headquarter
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  # sanity:
  #   name: Sanity check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '24.x'
  #         cache: 'npm'
  #         cache-dependency-path: './package-lock.json'
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Try hitting a build
  #       run: npm run build

  deploy:
    name: Deploy on HQ
    runs-on: ubuntu-latest
    # needs: sanity
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/dreamchasers
            git pull --rebase
            docker compose down
            docker compose build
            docker compose up -d
